name: flutter_share_content
description:
  Flutter plugin to share content to a generic app
  Picture, message and title are allowed
  Android supported
  iOS not supported
version: 0.2.1
author: Nadia Ghebreial Nieto <nadiagnieto@gmail.com>
homepage: https://github.com/NGhebreial/flutter_share_content
repository: https://github.com/NGhebreial/flutter_share_content

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.fluttersharecontent
    pluginClass: FlutterShareContentPlugin

